### ISSUE TITLE
Build Script for libevhtp repo http://gitlab.mero.colo.seagate.com/eos/third_party/libevhtp

### ISSUE THREAD

**Issue by ujjwalpl** [Seagate/cortx-posix#100]
The following discussion from #99 should be addressed:

- [ ] @ujjwal.lanjewar started a [discussion](http://gitlab.mero.colo.seagate.com/eos/fs/eos-fs/merge_requests/99#note_32065):  (+4 comments)

    > rename this to build.sh

**Comment by sachinpunadikar** [comment]
Closing this issue, as required packages are mentioned in spec file as required for build.
