### ISSUE TITLE
Upgrade NFS Ganesha build script

### ISSUE THREAD

**Issue by ivan-alekhin** [Seagate/cortx-posix#104]
The initial version of `build-nfs-ganesha.sh` script has not-implemented parts (for instance, rpm-install/uninstall commands) and some inconsistencies (the list of dependencies should be hardcoded and it should be integrated with the cmake configure step. For example, it either should force all the components to use jemalloc or force all the components not to use jemalloc).

Related issue for libevhtp: http://gitlab.mero.colo.seagate.com/eos/fs/eos-fs/issues/2

**Comment by cortx-admin** [comment]
> Mark Wiggins commented in Jira Server:

Closing NFS tickets

**Comment by cortx-admin** [comment]
> Mark Wiggins commented in Jira Server:

Closing NFS tickets
