### ISSUE TITLE
Follow-up from "EOS-5086: Automated Unit testing and grouping according to modules"

### ISSUE THREAD

**Issue by f7ed6454-82b8-4b41-a760-ff0aa27bf5e5** [Seagate/cortx-posix#119]
The following discussion from #105 should be addressed:

- [ ] @ivan.alekhin started a [discussion](http://gitlab.mero.colo.seagate.com/eos/fs/eos-fs/merge_requests/103#note_36895):  (+1 comment)

    > Let's consider adding a new command "ctest" into build.sh script and integrating each set of test groups with that:
    > 
    > ```
    > # Runs all tests which name starts with "regression-"
    > ./scripts/build.sh ctest regression-*
    > # calls the following commands
    > # ./dsal/scripts/build.sh ctest regression-*
    > # ./nsal/scripts/build.sh ctest regression-*
    > # and so on.
    > 
    > # Each of this command calls the following thing:
    > # cd $CMAKE_BUILD_DIR
    > # sudo ctest regression-*
    > 
    > # Also we will have per-module commands:
    > 
    > # Runs DSAL tests which name starts with "write-"
    > ./scripts/build.sh dsal ctest write-*
    > ```
    > 
    > cc @ujjwal.lanjewar , @rohan.puri , @shraddha.shinde

**Comment by mukul-seagate11** [comment]
Thanks for opening this issue. A contributor should be by to give feedback soon. In the meantime, please check out the https://github.com/Seagate/cortx/blob/main/CONTRIBUTING.md and explore other https://github.com/Seagate/cortx/

**Comment by cortx-admin** [comment]
> Mark Wiggins commented in Jira Server:

Closing NFS tickets

**Comment by cortx-admin** [comment]
> Mark Wiggins commented in Jira Server:

Closing NFS tickets
