### ISSUE TITLE
Inconsistent

### ISSUE THREAD

**Issue by raikrahul** [Seagate/cortx-posix#302]
https://github.com/Seagate/cortx-posix/blob/75444900f98f248c49c7db21be5a1603bfe70aba/experiments/readdir_profiling.c#L190

**Comment by mukul-seagate11** [comment]
Thanks for opening this issue. A contributor should be by to give feedback soon. In the meantime, please check out the https://github.com/Seagate/cortx/blob/main/CONTRIBUTING.md and explore other https://github.com/Seagate/cortx/
