### ISSUE TITLE
Why does SEAGATE Have JIRA Names in the commit messages? It's neither useful nor meaningful.

### ISSUE THREAD

**Issue by raikrahul** [Seagate/cortx-posix#303]
Exactly what do the employees of Seagate think when they tell the rest of github that they have fixed JIRA?

Figuring out Seagate's employee's intent by reading their code, seeing the code quality, reading the poor English in the documents,  is already hard enough.

It's not very hard to have empathy with the rest of github users.

**Comment by mukul-seagate11** [comment]
Thanks for opening this issue. A contributor should be by to give feedback soon. In the meantime, please check out the \[contributing guidelines\](https://github.com/Seagate/cortx/blob/main/CONTRIBUTING.md) and explore other \[ways you can get involved\](https://github.com/Seagate/cortx/)
