### ISSUE TITLE
Why does one have comments in the file and have commented code?

### ISSUE THREAD

**Issue by raikrahul** [Seagate/cortx-posix#305]
Please make sure to not bring the overall quality of github down when you upload a file with code section commented out.

**Comment by mukul-seagate11** [comment]
Thanks for opening this issue. A contributor should be by to give feedback soon. In the meantime, please check out the https://github.com/Seagate/cortx/blob/main/CONTRIBUTING.md and explore other https://github.com/Seagate/cortx/
